### PR TITLE
More efficient query for all persistenceIds, #742

### PR DESCRIPTION
**Pull request by patriknw**
* new table all_persistence_id
* not using metadata table to avoid risk of overwriting deleted_to, and
  would be more difficult for migration tool to insert or update
* persistenceId is inserted when first event is written
* Cleanup tool also deletes from all_persistence_id
* Migration support in Reconciliation tool
* table definition in KeyspaceAndTableStatements (which updates docs)

Refs #742

### CODE REVIEW

**Comment by chbatey** [comment]
One change here is that the insertion of the first event is no longer atomic with the persistence id appearing in the persistence id query. 

I think this is what is making the events by tag migration spec fail.

**Comment by patriknw** [comment]
Fixed the EventsByTagMigrationSpec. The problem was that the test is using direct writing and then the all_persistence_ids table wasn't updated. Fixed by dd5dff59

**Comment by chbatey** [comment]
Aha 👍

**Comment by chbatey** [comment]
Conflict. I'll fix

**Pull request merged**
