### PR TITLE
Document how to fix the driver/jvm to be able to survive a cassandra …

### PR DESCRIPTION
**Pull request by danischroeter**
…rolling restart on kubernetes - or generally dns/ip changes...

References #445

### CODE REVIEW

**Comment by dispalt** [comment]
This has been working well for us in production on a dynamic cluster (Astra)

**Comment by danischroeter** [comment]
@octonato @patriknw any chance this can get merged? People running into this will waste a lot of time finding this out again...

**Review by patriknw — APPROVED** [review]
LGTM

**Review by octonato — APPROVED** [review]
LGTM

**Pull request merged**
