### PR TITLE
Fix read journal metrics category in multi-plugin scenario - release-0.50

### PR DESCRIPTION
**Pull request by migesok**
* also uses improvements made in akka/akka#19822 to unify metrics
  category logic for all plugins: write, read and snapshot store

## Purpose

Fixes read journal Cassandra client metrics category when multiple instances of the plugin used - for MV-based eventsByTag version (`release-0.50`)

## References

References #579, #580

## Changes

* read, write and snapshot store plugins now use config path for metrics categories

### CODE REVIEW

**Comment by ihostage** [comment]
README:

> 0.50+ (currently 0.62) -> release-0.50- first release under this organisation, previously under krasserm. No planned releases for this version.

🤷‍♂

**Comment by migesok** [comment]
@ihostage I use an internal fork of 0.62, just wanted to contribute back some of my fixes.
I've also made a PR fix for the master: #580

**Comment by ihostage** [comment]
@migesok I understand. 😉Just I doubt that the maintainer will merge this PR because branch `0.50+` is freeze. 🤷‍♂

**Comment by chbatey** [comment]
Looks like the travis file for this branch is broken due to JDK versions. I'll fix that now then we can rebase this PR

**Comment by migesok** [comment]
Merged the travis build fix from the release-0.50 branch.

**Comment by chbatey** [comment]
Thanks @migesok

**Pull request merged**
