### PR TITLE
rename whitesource stable name to include minor version

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by raboof** [comment]
Interesting, this PR is now failing because "Some dependencies were rejected by the organization's policies". Too bad it doesn't document which dependencies were rejected and why...

**Comment by patriknw** [comment]
strange, it shouldn't be different for non stable releases

**Comment by patriknw** [comment]
it's jnr-posix, I'll try to exclude it
https://groups.google.com/a/lists.datastax.com/forum/#!topic/java-driver-user/ONpgXJyqTu0

**Comment by patriknw** [comment]
looks like we will be able to include jnr-posix after all (thanks to the ECP license), I'll revert and complete this PR when that has been sorted out

**Pull request merged**
