### PR TITLE
Upgrade to akka 2.4.9

### LINKED ISSUE #118: Upgrade to akka 2.4.9

### PR DESCRIPTION
**Pull request by franbh**
It would be great if you could release a version including this PR, if timing allows.

Closes #118

### CODE REVIEW

**Comment by patriknw** [comment]
Thanks.
Note that you can use current 0.17 version with akka 2.4.9, since Akka releases are binary backwards compatible.

**Comment by franbh** [comment]
Thanks for merging the PR!

Yes, I'm aware of the binary compatibility, but according to the Akka Docs there is no binary compatibility for experimental modules (http://doc.akka.io/docs/akka/2.4.9/common/binary-compatibility-rules.html#meaning-of-experimental). Since akka-persistence-cassandra depends on akka-persistence-query-experimental, I thought it was unsafe to use current 0.17 version with akka 2.4.9.
Once again, there is no problem whatsoever if you can't release a version right now.

**Comment by patriknw** [comment]
Yeah you are right, in theory. We have not changed persistence-query so it's not a problem right now. We will of course cut a new release, but it doesn't have to be driven by this change.

**Comment by franbh** [comment]
Thanks for the explanation @patriknw , keep up the good work! :)

**Pull request merged**
