### PR TITLE
Only log if test fails (copied from WithLogCapturing in akka/akka)

### PR DESCRIPTION
**Pull request by chbatey**

### CODE REVIEW

**Comment by raboof** [comment]
Travis now fails the tests builds because they produce too much logging... would it help if we only run the `EventsByTagSpec` in this branch, and repeat until we see the failure?

**Comment by chbatey** [comment]
Yep i won't merge this

**Comment by jrudolph** [comment]
Maybe copy over the `WithLogCapturing` tools from akka to log only on failures if that helps?

**Comment by chbatey** [comment]
> Maybe copy over the WithLogCapturing tools from akka to log only on failures if that helps?

:+1: 

The really verbose logs are from another test (writes 1000s of events) that shared config with the failing one so I'll override that one to INFO.

**Comment by chbatey** [comment]
I've been re-unning this but hasn't failed. I'll merge so master builds have reduced logging and pick up the DEBUG logs for this failure

**Pull request merged**
