### PR TITLE
Update sbt-header plugin to 1.6.0 #150

### PR DESCRIPTION
**Pull request by lukas-phaf**
* sbt-header 1.6.0 fixes problems with newlines on Windows

### CODE REVIEW

**Comment by lukas-phaf** [comment]
The test failures look like intermittent failures, unrelated to the change.

Although I don't think it is related, I tried running the tests several times locally, both with sbt-header 1.5.1 and 1.6.0. Both versions sometimes fail.

How should I proceed?

**Comment by patriknw** [comment]
some timeout, don't think we have changed anything related to that. I have restarted the ci job

**Comment by lukas-phaf** [comment]
@patriknw, it looks like another intermitten timeout error. Can you restart the CI job?

**Comment by johanandren** [comment]
PLS BUILD

**Comment by patriknw** [comment]
this is Travis, must be restarted from UI, I did that

**Comment by lukas-phaf** [comment]
Thanks. Looks good now.

**Comment by patriknw** [comment]
Refs #150

**Pull request merged**
