### PR TITLE
Correct JDK names for Jabba

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by patriknw** [comment]
restarted travis job - The job exceeded the maximum log length, and has been terminated.

**Comment by ennru** [comment]
Isn't this fixed already?

https://github.com/akka/akka-persistence-cassandra/blob/master/.travis.yml#L15

**Comment by patriknw** [comment]
ok, I'll change to that commit, but please remember to backport to the release-0.x branch going forward (I have noticed several things that were out of sync)

**Comment by patriknw** [comment]
EventsByTagSpec seems to fail sometimes, merging anyway because without this pr validation doesn't work at all

**Pull request merged**
