### PR TITLE
Try using apt...

### PR DESCRIPTION
**Pull request by ignasi35**
References #881

### CODE REVIEW

**Comment by ignasi35** [comment]
Test jobs take about 45min

**Review by patriknw — APPROVED** [review]
LGTM, note that the dispatcher stuff was merged into this PR

**Comment by ignasi35** [comment]
> note that the dispatcher stuff was merged into this PR

🤦🏼‍♂️ I merged them in the wrong order

**Comment by patriknw** [comment]
@ignasi35 pls squash next time to avoid wip commits in the main/release branches

**Pull request merged**
