### PR TITLE
Review feedback for PR #429

### PR DESCRIPTION
**Pull request by chbatey**
This is https://github.com/akka/akka-persistence-cassandra/pull/429/files

along with the review feedback

Don't merge this as i'll manually squash to ensure credit is given to original author

### CODE REVIEW

**Comment by patriknw** [comment]
strange name of this PR?

**Comment by chbatey** [comment]
Caught another case where the next query was kicked off before the previous one was fully fetched

**Comment by chbatey** [comment]
Squashed and can be merged once validation has completed

**Comment by chbatey** [comment]
Needs back ported to release-0x branch

**Pull request merged**
