### PR TITLE
don't cache failed prep stmts, #89

### PR DESCRIPTION
**Pull request by patriknw**
* When the inital connect failed e.g. because Cassandra
  was not started yet the prepared statements were cached
  as failed futures and would never reconnect.
* Place the cache in the CassandraSession instead and
  remove failed from cache.

### CODE REVIEW

**Comment by patriknw** [comment]
Fixes #89

**Comment by ktoso** [comment]
LGTM, great detective work! 🔍

**Comment by jypma** [comment]
The cache here looks a lot like the one that was in spray, and hasn't been pulled along into akka-http. I've maintained a modern akka variant of it [here], including a Java-friendly version. 

Would it make sense to have something cache-like in akka or contrib?

**Comment by patriknw** [comment]
This is just a `Map`, but I do think we have (or will have) need for an efficient LRU cache in akka (or as a dependency).

**Pull request merged**
