### PR TITLE
Client SSL auth optional

### PR DESCRIPTION
**Pull request by magnusart**
New try, now against master. All the tests passed locally.

Commit:
- Added support for connecting to cassandra clusters without client auth
- Regenerate and updated documentation around security and keystrokes
- Expanded .gitignore
- Updated README to reflect client auth changes
- Now uses cassandra-driver-core 3.0.0-rc1

### CODE REVIEW

**Comment by patriknw** [comment]
LGTM, thanks a lot @magnusart I'll give other a chance to look at it, and merge within a few days

**Comment by magnusart** [comment]
Cool, thanks.

**Comment by mattelacchiato** [comment]
It would be nice to be able to configure your own cipher suites... But I would agree that this could be done in a different PR...

**Comment by magnusart** [comment]
Please create an issue and we can add it. Is this a new feature of the 3x driver? 

I'm actually curious of the use case for limiting chiper suites in the scope of Akka Persistence cassandra? You usually have control over both the server and the client.

**Comment by mattelacchiato** [comment]
Ah, just had another look into the code. In 2.x you would use the datastax' default cipher suites, which were "TLS_RSA_WITH_AES_128_CBC_SHA" and "TLS_RSA_WITH_AES_256_CBC_SHA" only.

Just realised that this isn't the fact anymore in 3.x

**Comment by patriknw** [comment]
thanks for a great contribution, @magnusart 
keep 'em coming

**Pull request merged**
