### PR TITLE
Include public API for CassandraSession, #111

### PR DESCRIPTION
**Pull request by patriknw**
* Both Scala and Java API
* It's a merge of previous CassandraSession in this project
  and the additional functionality that Lagom's CassandraSession
  provided. Lagom will use this one (delegate to it).

### CODE REVIEW

**Comment by patriknw** [comment]
Refs #111

**Comment by patriknw** [comment]
@johanandren please review

**Comment by notxcain** [comment]
Awesome, thanks for this PR @patriknw! Do I understand right that in order to create some tables I need to create another `CassandraSession` and use `init` hook and it will be serialized using `CassandraSession$#serializedExecution` and prevent nasty Cassandra schema errors?

**Comment by patriknw** [comment]
@notxcain Yes, you can use the `init` hook to do stuff before the underlying session is used by other methods. I'm not using `serializedExecution` of the `init`. I did a naive attempt, but it doesn't work. We can investigate it further if it it's a real problem to serialize execution of custom init with the journal init. I dislike this "hack" in general.

**Comment by patriknw** [comment]
@johanandren There is only api docs in this project. At some point we might want to add Paradox here also. I'll create a ticket.

**Pull request merged**
