### PR TITLE
Improve error handling if Cassandra node is down #145

### PR DESCRIPTION
**Pull request by lukas-phaf**

### CODE REVIEW

**Comment by kpbochenek** [comment]
Won't in that case `onUnavailable` be called instead?

**Comment by lukas-phaf** [comment]
Yes, that is what I expected as well. But in the [documentation](https://datastax.github.io/python-driver/api/cassandra/policies.htmll) it says:
`on_unavailable(query, consistency, required_replicas, alive_replicas, retry_num)
This is called when the coordinator node determines that a read or write operation cannot be successful because the number of live replicas are too low to meet the requested ConsistencyLevel. This means that the read or write operation was never forwared to any replicas.`

So, onUnavailable is called when the coordinator (server) has trouble reaching other replicas, but not when the coordinator itself can not be reached.

**Comment by lukas-phaf** [comment]
Here is some additional info on this:
http://docs.datastax.com/en/developer/java-driver/3.1/manual/retries/

**Comment by patriknw** [comment]
Refs #145

**Comment by patriknw** [comment]
Thanks @lukas-phaf

**Pull request merged**
