### PR TITLE
Rewrite secrets to travis.com

### PR DESCRIPTION
**Pull request by ignasi35**
References https://github.com/akka/akka-meta/issues/143

### CODE REVIEW

**Comment by ignasi35** [comment]
We may want to backport this to stable branches (but I'd rather hold until we need to do a relese from the stable branch).

**Comment by chbatey** [comment]
I am missing some context, how do we switch over? I'll assume you know what you are doing :)

**Review by chbatey — APPROVED** [review]

**Comment by ignasi35** [comment]
> I am missing some context, how do we switch over? I'll assume you know what you are doing :)

Using travis-ci.com tools the migration is handled by travis infrastructure. The build for this PR was already run on travis-ci.com (https://travis-ci.com/github/akka/akka-persistence-cassandra/builds/197923907).

The missing bit on the migration (which can't be managed by travis infrastructure) is we need to re-encrypt secrets (which this PR does).

Here's an equivalent PR in other repos: https://github.com/akka/akka-persistence-dynamodb/pull/97

We'll know if I encrypted the correct secrets when we run a publish or a whitesource check that uses them :-)

**Comment by ignasi35** [comment]
There's, at least one error in this PR: https://travis-ci.com/github/akka/akka-persistence-cassandra/builds/198217951

**Pull request merged**
